### ISSUE TITLE
能否告知一下判断依据

### ISSUE THREAD

**Issue by PackageInstaller** [xiayingLIULI/zhenxun_plugin_QQweight#1]
我感觉不准啊，我朋友权重30202，但是莫名被封30天，我号最低，只有400多，但是一直没事，是不是反了，分越高越危险

**Comment by xiayingLIULI** [comment]
> 我感觉不准啊，我朋友权重30202，但是莫名被封30天，我号最低，只有400多，但是一直没事，是不是反了，分越高越危险

这个仅供参考，具体情况要看腾讯的，如果被人手动举报，分数再高也是无效的。权重分的计算就是活跃度、等级、会员等级、违规记录以及消费的综合计算。

**Comment by xiayingLIULI** [comment]
> 我感觉不准啊，我朋友权重30202，但是莫名被封30天，我号最低，只有400多，但是一直没事，是不是反了，分越高越危险

只能保证自己在不违规的情况下能保证号的安全，我的bot号权重是0天天封号。

**Comment by PackageInstaller** [comment]
感谢告知
